replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 80

ingress:
  enabled: true  # Ensure ingress is enabled
  className: "nginx"
  annotations:
    nginx-trial: "true"  # Added nginx-trial annotation as defined in task requirement
  hosts:
    - host: payever.task.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
